// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/ledger.proto

package ledgerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SenderAccount   string                 `protobuf:"bytes,1,opt,name=sender_account,json=senderAccount,proto3" json:"sender_account,omitempty"`
	ReceiverAccount string                 `protobuf:"bytes,2,opt,name=receiver_account,json=receiverAccount,proto3" json:"receiver_account,omitempty"`
	Amount          int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	ReferenceId     string                 `protobuf:"bytes,4,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_proto_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *TransferRequest) GetSenderAccount() string {
	if x != nil {
		return x.SenderAccount
	}
	return ""
}

func (x *TransferRequest) GetReceiverAccount() string {
	if x != nil {
		return x.ReceiverAccount
	}
	return ""
}

func (x *TransferRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_proto_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *TransferResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransferResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_ledger_proto protoreflect.FileDescriptor

const file_proto_ledger_proto_rawDesc = "" +
	"\n" +
	"\x12proto/ledger.proto\x12\x06ledger\"\x9e\x01\n" +
	"\x0fTransferRequest\x12%\n" +
	"\x0esender_account\x18\x01 \x01(\tR\rsenderAccount\x12)\n" +
	"\x10receiver_account\x18\x02 \x01(\tR\x0freceiverAccount\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12!\n" +
	"\freference_id\x18\x04 \x01(\tR\vreferenceId\"Q\n" +
	"\x10TransferResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2N\n" +
	"\rLedgerService\x12=\n" +
	"\bTransfer\x12\x17.ledger.TransferRequest\x1a\x18.ledger.TransferResponseB\x10Z\x0eproto/ledgerpbb\x06proto3"

var (
	file_proto_ledger_proto_rawDescOnce sync.Once
	file_proto_ledger_proto_rawDescData []byte
)

func file_proto_ledger_proto_rawDescGZIP() []byte {
	file_proto_ledger_proto_rawDescOnce.Do(func() {
		file_proto_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ledger_proto_rawDesc), len(file_proto_ledger_proto_rawDesc)))
	})
	return file_proto_ledger_proto_rawDescData
}

var file_proto_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ledger_proto_goTypes = []any{
	(*TransferRequest)(nil),  // 0: ledger.TransferRequest
	(*TransferResponse)(nil), // 1: ledger.TransferResponse
}
var file_proto_ledger_proto_depIdxs = []int32{
	0, // 0: ledger.LedgerService.Transfer:input_type -> ledger.TransferRequest
	1, // 1: ledger.LedgerService.Transfer:output_type -> ledger.TransferResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ledger_proto_init() }
func file_proto_ledger_proto_init() {
	if File_proto_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ledger_proto_rawDesc), len(file_proto_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ledger_proto_goTypes,
		DependencyIndexes: file_proto_ledger_proto_depIdxs,
		MessageInfos:      file_proto_ledger_proto_msgTypes,
	}.Build()
	File_proto_ledger_proto = out.File
	file_proto_ledger_proto_goTypes = nil
	file_proto_ledger_proto_depIdxs = nil
}
