syntax = "proto3";

package payment;

option go_package = "proto/paymentpb";

service PaymentService {
  rpc CreatePayment(CreatePaymentRequest) returns (CreatePaymentResponse);
  rpc GetPayment(GetPaymentRequest) returns (GetPaymentResponse);
}

message CreatePaymentRequest {
  string sender_account = 1;
  string receiver_account = 2;
  int64 amount = 3;
  string currency = 4;
}

message CreatePaymentResponse {
  string payment_id = 1;
  string status = 2;
}

message GetPaymentRequest {
  string payment_id = 1;
}

message GetPaymentResponse {
  string payment_id = 1;
  string status = 2;
  int64 amount = 3;
}
